### ISSUE TITLE
Rename this project

### ISSUE THREAD

**Issue by RussellLuo** [RussellLuo/kok#22]
## Motivation

In some cultures, the pronunciation of `kok` may lead to misunderstanding. (See comments [here](https://www.reddit.com/r/golang/comments/oe62xx/kok_v030_add_support_for_grpc_apis/) and [here](https://www.reddit.com/r/golang/comments/qwr5hr/kok_v040_redesign_the_annotation_syntax/).)

## New name

The new name under consideration is `kin`, which means "**K**in **I**s **N**ot just a kit of Go kit".

Other related names:
- Module path
    + github.com/RussellLuo/kin
- Code generation tool
    + `kingen`
- Annotation directives
    + `//kin:op`
    + `//kin:param`
    + `//kin:body`
    + `//kin:success`
    + `//kin:oas`
    + `//kin:alias`
    + `//kin:grpc`
- Struct tags
    + `kin:"..."`

## Tasks

- Rename the repo
- Update the code
- Update the docs

**Comment by gedw99** [comment]
Kin might not be a good idea as there is a golang lib with the same name that does open api introspection. 

https://github.com/getkin

**Comment by gedw99** [comment]
I agree that the current name is offensive on English .

what about “blok” ? It’s a play on works of “block” . Your project is designed to use blocks of things stacked up on top of each other to produce the final result.

“Blok” is also sort of similar and funky like “kok”

**Comment by RussellLuo** [comment]
@gedw99 Thanks for your suggestions!

Initially, this project is designed to be a code generation tool for Go kit, in order to reduce the burden of handwriting boilerplate code.

As the project evolves, I increasingly find that it will concentrate on handling the communications between services, to free developers to focus on the business logic. Ultimately, the project may support the following communication types:
- In-process function call
- RPC (e.g. HTTP and gRPC)
- Asynchronous messaging (not supported yet)

Therefore, as for the new name, I think a better alternative may be `kom`, which is derived from "com" (short for "communication") with the leading "c" being replaced with "k".

**Comment by gedw99** [comment]
Sounds awesome 

i would like to try to add async communication generators .

i use NATS quite a bit . It’s a message bus and broker . 

https://github.com/nats-io/nats.go

It has HTTP / web socket and tcp transports built in. 

So for iot people use the tcp layer .
But for web they use the http and web sockets . 

Nats is globally clustered , self load balancing and has build in security. It also has a clustered kv that replaced etc and consul.
So it remove the need for a lot of other layers typically needed for global internet scale systems engineering . 

It’s 109% golang and runs on anything .

It can do RPC and PUB SUB also.

You can use protobufs, json , anything you want serialisation . It does not care .

I don’t know how familiar you are with NATS . But just let me know if this is something if interest.

i currently use it in iot, web, desktop and servers .

**Comment by RussellLuo** [comment]
For those who don't know, Ged has suggested that `kom` might not be a good idea.

Now I'm considering renaming this project to `kun`, which is "鲲" in Chinese. The idea is inspired by [chi](https://github.com/go-chi/chi), whose name is from "qi" (气) in Chinese (see [here](https://github.com/go-chi/chi/issues/199#issuecomment-303135420)).
